name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: BoxBuild-ify
      run: ./boxbuildify.sh

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci -ws --include-workspace-root

    - name: Fix ESM import paths
      run: npm run fix-esm-import-path

    - name: Build
      run: npm run build -ws

    - name: Set version
      id: set-version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Configure packages
      run: |
        # Ensure packages are linked to this repository
        for pkg in expressions languageserver languageservice workflow-parser; do
          pushd $pkg
          contents=$(jq --arg v "$VERSION" --arg repo "$GITHUB_REPOSITORY" \
            '.version = $v | 
            .repository = {
              "type": "git",
              "url": "git+https://github.com/$repo.git"
            } |
            .publishConfig = {
              "registry": "https://npm.pkg.github.com"
            }' package.json)
          echo "$contents" > package.json
          popd
        done

    - name: Publish packages
      run: |
        # Setup auth for npm publish
        echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        echo "@boxbuild-io:registry=https://npm.pkg.github.com" >> .npmrc
        
        for pkg in expressions languageserver languageservice workflow-parser; do
          pushd $pkg
          npm publish
          popd
        done
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
